### ISSUE TITLE
Copied from Facebook discussion

### ISSUE THREAD

**Issue by DrHyde** [DrHyde/perl-modules-Scalar-Type#3]
Bill Ricker said ...

ok, the POD is perhaps ambiguous. 

I think I'd rather get an error for 5.34 or lower (< 5.35.7) at use Scalar::Type qw/is_bool/ time than at execution. "Bad news early is good."

The POD also discusses pre-modern inference  on NV/IV=1 or 0 exactly, or PV="" which doesn't strictly require XS access but might for speed. 

My question is really why rather than erroring for Perl Too Old, this function doesn't fall back to that quaint inspection of the values when perl too old. 

(Presumably differential compilation could avoid runtime inefficiency of testing Perl version at every usage?)

**Comment by n1vux** [comment]
(that me. watching.)

**Comment by DrHyde** [comment]
Made fatal at import-time in 71c3cce

**Comment by DrHyde** [comment]
I've also tweaked the doco, if there's anything else you think could be improved please let me know!
